### ISSUE TITLE
Strange symbols in listview

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_fontawesome#1]
Ubuntu 17.4, 3 fonts are installed from your zip.
look how "hdd" it shown.

![font-pl](https://user-images.githubusercontent.com/4154978/35184484-59408cd6-fe07-11e7-8204-a936542af55e.png)

**Comment by TomBraider42** [comment]
I hade to add a (in Windows) non visible character after every char of the name.
The fonts replaces the codes automatically with the icons. So "angellist" shows "angle" and the list icon.
You can test it using on of these fonts in an text editor and type "taxi".
See the first, hidden column of this list. These are the real names without special chars for the search.

![unbenannt](https://user-images.githubusercontent.com/5128016/35187231-d369c7ac-fe20-11e7-9a8d-3981df049e9b.PNG)

The best way would be to use an other font for the Text column but i thing this is impossible.
Any Idea? I only have windows.

**Comment by Alexey-T** [comment]
other font for other column? not possible.
can u test `if os.name=='nt'` and add char only on Win?

**Comment by Alexey-T** [comment]
Idea 2) Use type "listbox_ex" and paint any text by any font in any column.
Plugin "Insert Emoji" -example.

**Comment by Alexey-T** [comment]
Idea 3) https://en.wikipedia.org/wiki/Zero-width_space

**Comment by TomBraider42** [comment]
Can you change line 136 from
`items = items + '\t'.join(code[0] + '\r ' + chr(int(code[1], 16)) + '\r' + u'\u0080'.join(list(code[0])) for code in self.codes)`
to
`items = items + '\t'.join(code[0] + '\r ' + chr(int(code[1], 16)) + '\r' + u'\u200B'.join(list(code[0])) for code in self.codes)`
It is idea 3 and works for Windows too. But in Linux?
Shows the first column the correct names in Linux? Than i can use the first idea.
But the second seams to be the best and cleanest way.

**Comment by Alexey-T** [comment]
Idea3) if I change to `\u200B` then it looks like
![plug-now](https://user-images.githubusercontent.com/4154978/35196668-55b55c92-fee6-11e7-9610-971322231817.png)

**Comment by Alexey-T** [comment]
Best is do it like "Insert Emoji" plg.

**Comment by TomBraider42** [comment]
Changed from listview to listbox_ex. Looks good in Windows but in Linux?

BTW: is there an filter field (with default text and delete button) for listbox_ex too?

**Comment by Alexey-T** [comment]
You should add controls to make this filter, like InsertEmoji does

**Comment by Alexey-T** [comment]
looks OK now, tks.
