### ISSUE TITLE
add "api=" in .inf

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_fontawesome#2]
Pls del line
MIN_VERSION = '1.34.1'

and add `api=1.0.mmmm` in install.inf, it is faster.

**Comment by TomBraider42** [comment]
Will change it.
But now there is no message if the user installs the plugin manually, right?

**Comment by Alexey-T** [comment]
no message, if no "api=" line in install.inf.
with "api=" AddonManager tells it.
