### ISSUE TITLE
Listbox has white (too lite) and pale gray (not visible)

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_fontawesome#4]
Linux test
![font-pl](https://user-images.githubusercontent.com/4154978/35293253-3afb8d64-0084-11e8-8eda-212ec5f64f28.png)

**Comment by TomBraider42** [comment]
Don't understand. The problem is the white background?
Now changed to `COLOR_ID_TextBg`.
I found some IDs in `cudatext.py`. But can i find/use colors like "treeview, BG" from theme settings dialog? I think the treeview are the best color constellation.

**Comment by Alexey-T** [comment]
Picture shows white BG color for empty listbox area
It must be themed color or some darker color (API to get theme colors is limited, COLOR_ID_*)

b) Pic shows white BG for filter box.

**Comment by TomBraider42** [comment]
If the colors should work with all themes we need a more complete API.
I now use (not uploaded) COLOR_ID_TextFont and COLOR_ID_TextBg for the list and COLOR_ID_CurLineBg for selected line.
The combo_bo will not be styled? Looks wrong in dark themes.

**Comment by Alexey-T** [comment]
About new api, see my reply in CudaText issues 1207

About combo box. You need type:button_ex with button_proc() and Kind:btnkind_text_choice

**Comment by TomBraider42** [comment]
Ok, new API works and tree colors will be used.

But the font values will be ignored?
```
n = dlg_proc(h, DLG_CTL_ADD, 'button_ex')
dlg_proc(h, DLG_CTL_PROP_SET, index=n, prop={'font_name': ..., 'font_size': ...  })
```
And `button_proc(self.h_font, BTN_SET_ARROW_ALIGN, 'L')` will places the arrow like this.

![unbenannt](https://user-images.githubusercontent.com/5128016/35327667-802d4104-00fa-11e8-9a6c-6a48fd46b27e.PNG)

**Comment by Alexey-T** [comment]
1- button_ex ignores font_NNNN settings.
2- Set BTN_SET_ARROW_ALIGN to 'R'

**Comment by Alexey-T** [comment]
Ah- 'L' value give not ok look. can you give tiny plugin to test?

**Comment by Alexey-T** [comment]
3- will check look with 'L' value, maybe text_choice is not ok with 'L'.

**Comment by TomBraider42** [comment]
you can use my current version [cuda_fontawesome.zip](https://github.com/TomBraider42/cuda_fontawesome/files/1659588/cuda_fontawesome.zip)
'L' is the best choice because the drop down field is at the left too.

**Comment by Alexey-T** [comment]
Arrow on right- don't mean that I must click on right, i can click on left. so it;s ok.
b) You can paint unicode dropdown arrow on caption.

**Comment by Alexey-T** [comment]
Pls set "FOCUSABLE" for text-choise to False.

**Comment by Alexey-T** [comment]
Pls set back-color of filter editor.

**Comment by TomBraider42** [comment]
I know i can click everywhere!
But if i click on the right side because the arrow the there, i have to move the mouse to the left to the drop down field. The button is much wider as this field.
'C'enter is possible to if 'L' doesn't work.

![clipboard 1](https://user-images.githubusercontent.com/5128016/35330747-df71969c-0104-11e8-8db2-83d775ffac5d.png)
