### ISSUE TITLE
Fix needed

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_fontawesome#6]
a) for text-choice set FOCUSABLE to False
b) Can u set font_color and color for filter-edit?

theme "Cobalt" - filter NOT visible!

**Comment by Alexey-T** [comment]
c) dropdown arrow - must be aligned 'R' or use Unicode arrow on caption.

**Comment by TomBraider42** [comment]
Filter colors are set!
![unbenannt](https://user-images.githubusercontent.com/5128016/35330403-ad647ecc-0103-11e8-87bb-34f4fe40e3e5.PNG)
But how can i repaint the panel if theme was changed? Otherwise/now a restart is necessary to use the new colors.

**Comment by TomBraider42** [comment]
to c) What caption? There are only items.
`button_proc(self.h_font, BTN_SET_ITEMS, 'Solid\nRegular\nBrands')`
If i add an arrow it will be show in drop down list too.

**Comment by Alexey-T** [comment]
C) you are right, sorry
B) seems Ubuntu issue

**Comment by Alexey-T** [comment]
Added Cud issue for theme event
