### ISSUE TITLE
Can i publish plugin?

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_fontawesome#8]
I can make zip and publish

**Comment by TomBraider42** [comment]
yes, of course, that was the plan.

**Comment by Alexey-T** [comment]
I want Terminal (console cmd.exe) inside bottom panel, plugin, much. I can even give donate ..

**Comment by TomBraider42** [comment]
I have in projects tree context menu "Open in Commandline" which opens the cmd window.
Why in the panel with only round about 5 lines? Is it useful?
Btw, please post new issues like this in your cuda repository and not in my plugins. They're not connected.

**Comment by Alexey-T** [comment]
Yes, will post to my repo.

**Comment by Alexey-T** [comment]
Plugin published
